name: CI

on:
    pull_request:
        branches:
            - dev
            - main

jobs:
    frontend:
        name: Frontend CI
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: src/frontend/dtc-web

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm
                  cache-dependency-path: src/frontend/dtc-web/package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Build Angular application
              run: npm run build
